{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.databinding",
    "module": "adapters",
    "version": "7.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "7.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "adapters-7.1.1.aar",
          "url": "adapters-7.1.1.aar",
          "size": 81105,
          "sha512": "0f4c905515d7404a784684392b1861d72958af3bca2247377cb8d0767b384da6022e3857ac5c12b6937ff5fe4d04bb3afbdb6c46929f36e9dc33fdc8e234b474",
          "sha256": "64ce7f890fa91eb2c7da331686cd210c34c0c796e48a3d463f16f9d114c59961",
          "sha1": "9a461737ed0b9ae11eeb2e6e4c580b37b95038bd",
          "md5": "d00998a80d68a37e67a49ca5d9f97acd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.databinding",
          "module": "library",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "7.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "adapters-7.1.1.aar",
          "url": "adapters-7.1.1.aar",
          "size": 81105,
          "sha512": "0f4c905515d7404a784684392b1861d72958af3bca2247377cb8d0767b384da6022e3857ac5c12b6937ff5fe4d04bb3afbdb6c46929f36e9dc33fdc8e234b474",
          "sha256": "64ce7f890fa91eb2c7da331686cd210c34c0c796e48a3d463f16f9d114c59961",
          "sha1": "9a461737ed0b9ae11eeb2e6e4c580b37b95038bd",
          "md5": "d00998a80d68a37e67a49ca5d9f97acd"
        }
      ]
    }
  ]
}
